##
## Copyright (c) 2019 Matthias Tafelmeier.
##
## This file is part of godon
##
## godon is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, either version 3 of the
## License, or (at your option) any later version.
##
## godon is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this godon. If not, see <http://www.gnu.org/licenses/>.
##
services:
  build:
    image: squidfunk/mkdocs-material:9
    command: build --config-file /material/mkdocs.yml --site-dir /site
    volumes:
      - ./material:/material
      - ./docs:/site

  serve:
    image: squidfunk/mkdocs-material:9
    ports:
      - "9000:8000"
    command: serve --config-file /material/mkdocs.yml --dev-addr 0.0.0.0:8000
    volumes:
      - ./material:/material
